[build]
  command = "./build.js"
  publish = "build/"

[[redirects]]
  from = "https://the-infi-way.netlify.app"
  to = "https://way.infi.nl"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 1
    accessibility = 1
    best-practices = 1
    seo = 1
